// This file is auto-generated by the build script.
// Vercel routes all /api/* requests here via the catch-all [...path] handler.
// The _handler.cjs is a fully bundled Express app compiled by esbuild.
const { app } = require('./_handler.cjs');
module.exports = app;
